anchor_version = "0.17.0"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
staking_lockup = "HLVA2NmjGBsoKCwmGZg1zAYXFxMhKXRMf7V28RexGpcR"
staking_registry = "4wcKkwjthmfHd7CZNsCxnyZoEiujBLbDvJ7jDFjqoiKm"
ido_sale = "BvQQDMTy9XunH3muJaz6sckwpjyEeEvUqUowpSXBGVW7"

[programs.devnet]
staking_lockup = "HLVA2NmjGBsoKCwmGZg1zAYXFxMhKXRMf7V28RexGpcR"
staking_registry = "4wcKkwjthmfHd7CZNsCxnyZoEiujBLbDvJ7jDFjqoiKm"
ido_sale = "BvQQDMTy9XunH3muJaz6sckwpjyEeEvUqUowpSXBGVW7"

[scripts]
test = "mocha -t 1000000"
