[package]
name = "ido-sale"
version = "0.1.0"
description = "Created with Circlepod"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "ido_sale"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.17.0"
anchor-spl = "0.17.0"
